/* eslint-disable no-magic-numbers */

export const headers = {
  accept: "text/html, */*; q=0.01",
  "accept-language": "en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7",
  "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
  "sec-ch-ua": '"Chromium";v="133", "Not)A;Brand";v="24", "Google Chrome";v="133"',
  "sec-ch-ua-mobile": "?0",
  "sec-ch-ua-platform": '"Windows"',
  "sec-fetch-dest": "empty",
  "sec-fetch-mode": "cors",
  "sec-fetch-site": "same-origin",
  "x-requested-with": "XMLHttpRequest",
  cookie: process.env.COOKIE,
};

export const headersAnon = {
  accept: "text/html, */*; q=0.01",
  "accept-language": "en-US,en;q=0.9",
  "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
  priority: "u=1, i",
  "sec-ch-ua": '"Google Chrome";v="135", "Not-A.Brand";v="8", "Chromium";v="135"',
  "sec-ch-ua-mobile": "?0",
  "sec-ch-ua-platform": '"Windows"',
  "sec-fetch-dest": "empty",
  "sec-fetch-mode": "cors",
  "sec-fetch-site": "same-origin",
  "x-requested-with": "XMLHttpRequest",
};

export const WAIT_TIMES = {
  TENTH_SECOND: 0.1 * 1000,
  HALF_SECOND: 0.5 * 1000,
  ONE_SECOND: 1 * 1000,
  TWO_SECONDS: 2 * 1000,
  THREE_SECONDS: 3 * 1000,
  TEN_SECONDS: 10 * 1000,
  FIFTEEN_SECONDS: 15 * 1000,
  THIRTY_SECONDS: 30 * 1000,
  FIFTY_SECONDS: 50 * 1000,
  ONE_MINUTE: 1 * 60 * 1000,
  TWO_MINUTES: 2 * 60 * 1000,
  THREE_MINUTES: 3 * 60 * 1000,
  FIVE_MINUTES: 5 * 60 * 1000,
  TEN_MINUTES: 10 * 60 * 1000,
  FIFTEEN_MINUTES: 15 * 60 * 1000,
  THIRTY_MINUTES: 30 * 60 * 1000,
  SIXTY_MINUTES: 60 * 60 * 1000,
  TWO_HOURS: 120 * 60 * 1000,
  SIX_HOURS: 6 * 60 * 60 * 1000,
  TEN_HOURS: 10 * 60 * 60 * 1000,
  TWENTY_FOUR_HOURS: 24 * 60 * 60 * 1000,
};

export const rarities = {
  Easy: 1,
  Medium: 2,
  Unknown: 3,
  Hard: 4,
  Unown: 5,
  Rare: 6,
  Alola: 7,
  Galarian: 7,
  Galar: 7,
  Retro: 8,
  Starter: 9,
  Special: 10,
  Mysterious: 11,
  Mystery: 11,
  Legend: 12,
  Legendary: 12,
  Quest: 13,
  Event: 14,
  Ditto: 15,
};

export const URLs = [
  "https://pokeheroes.com/",
  "https://pokeheroes.com/about_pokeheroes",
  "https://pokeheroes.com/accessoires",
  "https://pokeheroes.com/account_settings",
  "https://pokeheroes.com/adventcalendar",
  "https://pokeheroes.com/ancient_cave",
  "https://pokeheroes.com/anniv_gift",
  "https://pokeheroes.com/apricornbattle",
  "https://pokeheroes.com/aprilfool2017",
  "https://pokeheroes.com/auction?id=",
  "https://pokeheroes.com/auction_house",
  "https://pokeheroes.com/auction_search",
  "https://pokeheroes.com/auction_search?search=all",
  "https://pokeheroes.com/auction_search?search=mega",
  "https://pokeheroes.com/auction_search?search=pokedex",
  "https://pokeheroes.com/auction_search?search=shiny",
  "https://pokeheroes.com/auction_setup.php",
  "https://pokeheroes.com/badges",
  "https://pokeheroes.com/bag",
  "https://pokeheroes.com/bagvalue",
  "https://pokeheroes.com/battle.php",
  "https://pokeheroes.com/battle_shop",
  "https://pokeheroes.com/battle_team",
  "https://pokeheroes.com/battle_user",
  "https://pokeheroes.com/bday",
  "https://pokeheroes.com/beach",
  "https://pokeheroes.com/beautycontest",
  "https://pokeheroes.com/berrybattle",
  "https://pokeheroes.com/berrydex",
  "https://pokeheroes.com/berrygarden",
  "https://pokeheroes.com/berrymarket",
  "https://pokeheroes.com/berrymarket?search=lorelei&amp;suser=&amp;sitem=Aguav+Berry&amp;slevel_min=1&amp;slevel_max=16",
  "https://pokeheroes.com/bill",
  "https://pokeheroes.com/browse_hashtag?tag=",
  "https://pokeheroes.com/browse_hashtag?tag=test",
  "https://pokeheroes.com/bugcontest",
  "https://pokeheroes.com/bulletinboard",
  "https://pokeheroes.com/buyeventpoints",
  "https://pokeheroes.com/celestica",
  "https://pokeheroes.com/change_avatar",
  "https://pokeheroes.com/change_birthdate",
  "https://pokeheroes.com/chat",
  "https://pokeheroes.com/cheat",
  "https://pokeheroes.com/christmasgift",
  "https://pokeheroes.com/christmasgift.php",
  "https://pokeheroes.com/clickback_list",
  "https://pokeheroes.com/clicklist",
  "https://pokeheroes.com/countdown",
  "https://pokeheroes.com/country_settings",
  "https://pokeheroes.com/darktober",
  "https://pokeheroes.com/daycare",
  "https://pokeheroes.com/doesitbreakmychain",
  "https://pokeheroes.com/ducklettweek",
  "https://pokeheroes.com/dw_collection",
  "https://pokeheroes.com/dw_collection?username=",
  "https://pokeheroes.com/dw_collection?username=Riako",
  "https://pokeheroes.com/dw_gift_log?username=",
  "https://pokeheroes.com/dw_gift_log?username=Riako",
  "https://pokeheroes.com/dw_points",
  "https://pokeheroes.com/dw_shop",
  "https://pokeheroes.com/easter",
  "https://pokeheroes.com/easter_buneary",
  "https://pokeheroes.com/edit_signature",
  "https://pokeheroes.com/emerabank",
  "https://pokeheroes.com/emerabank?nug",
  "https://pokeheroes.com/event_distribution",
  "https://pokeheroes.com/eventpass",
  "https://pokeheroes.com/eventshop",
  "https://pokeheroes.com/evolve.php?item=Fire%20Stone",
  "https://pokeheroes.com/fair",
  "https://pokeheroes.com/favoritevote",
  "https://pokeheroes.com/feedback",
  "https://pokeheroes.com/forum",
  "https://pokeheroes.com/forum_editpost.php?id=1899762",
  "https://pokeheroes.com/forum_newest_posts",
  "https://pokeheroes.com/forum_newpost.php?thread=27",
  "https://pokeheroes.com/forum_newthread.php?subforum=9",
  "https://pokeheroes.com/forum_subscriptions",
  "https://pokeheroes.com/forum_thread?id=26",
  "https://pokeheroes.com/fountain",
  "https://pokeheroes.com/friendlist",
  "https://pokeheroes.com/game_center",
  "https://pokeheroes.com/game_settings",
  "https://pokeheroes.com/gc_coinflip",
  "https://pokeheroes.com/gc_coinflip.php",
  "https://pokeheroes.com/gc_concentration",
  "https://pokeheroes.com/gc_hangman",
  "https://pokeheroes.com/gc_hangman?suggest",
  "https://pokeheroes.com/gc_hol",
  "https://pokeheroes.com/gc_hol.php",
  "https://pokeheroes.com/gc_lottery",
  "https://pokeheroes.com/gc_lottery.php",
  "https://pokeheroes.com/gc_lottery_tickets.php",
  "https://pokeheroes.com/gc_magearna",
  "https://pokeheroes.com/gc_prize_exchange",
  "https://pokeheroes.com/gc_prize_exchange.php",
  "https://pokeheroes.com/gc_wheel",
  "https://pokeheroes.com/gem_cauldron",
  "https://pokeheroes.com/gem_collector",
  "https://pokeheroes.com/gem_exchange",
  "https://pokeheroes.com/gem_exchange.php",
  "https://pokeheroes.com/gem_exchange.php?list=full",
  "https://pokeheroes.com/gem_exchange_offer?id=672063&amp;exchange=2752",
  "https://pokeheroes.com/gem_supplier",
  "https://pokeheroes.com/gem_supplier.php",
  "https://pokeheroes.com/gimmighoul",
  "https://pokeheroes.com/giratina",
  "https://pokeheroes.com/giveaway",
  "https://pokeheroes.com/giveawaycreator",
  "https://pokeheroes.com/golden_slot",
  "https://pokeheroes.com/golden_slot.php",
  "https://pokeheroes.com/golden_slot.php?mode=legend",
  "https://pokeheroes.com/golden_slot.php?mode=plus",
  "https://pokeheroes.com/gts",
  "https://pokeheroes.com/gts_my_offers",
  "https://pokeheroes.com/gts_my_trades",
  "https://pokeheroes.com/gts_new",
  "https://pokeheroes.com/gts_new?gift",
  "https://pokeheroes.com/gts_new?gift=Riako",
  "https://pokeheroes.com/gts_search",
  "https://pokeheroes.com/gts_search?type=0",
  "https://pokeheroes.com/gts_search?type=1",
  "https://pokeheroes.com/gts_search?type=2",
  "https://pokeheroes.com/gts_shop",
  "https://pokeheroes.com/gts_shop?history",
  "https://pokeheroes.com/gts_shop?type=2",
  "https://pokeheroes.com/gts_wondertrade",
  "https://pokeheroes.com/gts_wondertrade.php",
  "https://pokeheroes.com/gts_wondertrade.php?type=shiny",
  "https://pokeheroes.com/gts_wondertrade_history",
  "https://pokeheroes.com/gts_wondertrade_history?pkmnid=33903228",
  "https://pokeheroes.com/halloween",
  "https://pokeheroes.com/heritage?id=85072",
  "https://pokeheroes.com/herowalker",
  "https://pokeheroes.com/honeycomb",
  "https://pokeheroes.com/honeytree",
  "https://pokeheroes.com/index",
  "https://pokeheroes.com/interaction_stats",
  "https://pokeheroes.com/itemshop",
  "https://pokeheroes.com/iv",
  "https://pokeheroes.com/jirachi",
  "https://pokeheroes.com/kyurem?code=KYUR1062",
  "https://pokeheroes.com/lab",
  "https://pokeheroes.com/lovemeter",
  "https://pokeheroes.com/lovetest",
  "https://pokeheroes.com/lovetest?",
  "https://pokeheroes.com/mall",
  "https://pokeheroes.com/mall#mall",
  "https://pokeheroes.com/manage_contact",
  "https://pokeheroes.com/medal_rally",
  "https://pokeheroes.com/mentor",
  "https://pokeheroes.com/mermaid",
  "https://pokeheroes.com/misc_settings",
  "https://pokeheroes.com/moomoo",
  "https://pokeheroes.com/mysterybox.php",
  "https://pokeheroes.com/newest_adopts",
  "https://pokeheroes.com/notification_wall",
  "https://pokeheroes.com/notifications",
  "https://pokeheroes.com/odorcalibration",
  "https://pokeheroes.com/online",
  "https://pokeheroes.com/oras",
  "https://pokeheroes.com/paldearesearch",
  "https://pokeheroes.com/party",
  "https://pokeheroes.com/ph_features",
  "https://pokeheroes.com/pikapika",
  "https://pokeheroes.com/pm_inbox",
  "https://pokeheroes.com/pm_read?id=",
  "https://pokeheroes.com/pm_write",
  "https://pokeheroes.com/pm_write?to=Riako",
  "https://pokeheroes.com/pokedex",
  "https://pokeheroes.com/pokemon.php?id=18229384",
  "https://pokeheroes.com/pokemon?id=85072",
  "https://pokeheroes.com/pokemon_lite?cl_type=friend1",
  "https://pokeheroes.com/pokemon_lite?cl_type=friend2",
  "https://pokeheroes.com/pokemon_lite?cl_type=mass_Riako",
  "https://pokeheroes.com/pokemon_lite?cl_type=newest",
  "https://pokeheroes.com/pokemon_lite?cl_type=online",
  "https://pokeheroes.com/pokemon_lite?cl_type=random",
  "https://pokeheroes.com/pokemon_lite?cl_type=unreturned",
  "https://pokeheroes.com/pokemonrecovery",
  "https://pokeheroes.com/pokeradar",
  "https://pokeheroes.com/pokeradar_history",
  "https://pokeheroes.com/premium_features",
  "https://pokeheroes.com/premium_members",
  "https://pokeheroes.com/premium_settings",
  "https://pokeheroes.com/privacypolicy",
  "https://pokeheroes.com/profile_layout",
  "https://pokeheroes.com/profile_settings",
  "https://pokeheroes.com/puzzle",
  "https://pokeheroes.com/ranklist",
  "https://pokeheroes.com/raylong",
  "https://pokeheroes.com/referred_users",
  "https://pokeheroes.com/release",
  "https://pokeheroes.com/reshiram",
  "https://pokeheroes.com/reshrom",
  "https://pokeheroes.com/roaming?pokemon=shaymin&amp;end=1694390400",
  "https://pokeheroes.com/route53",
  "https://pokeheroes.com/royal_tunnel",
  "https://pokeheroes.com/rules",
  "https://pokeheroes.com/rumble",
  "https://pokeheroes.com/rumble_overview",
  "https://pokeheroes.com/rumble_overview.php",
  "https://pokeheroes.com/rumble_start.php",
  "https://pokeheroes.com/safari_zone",
  "https://pokeheroes.com/sale",
  "https://pokeheroes.com/salon",
  "https://pokeheroes.com/salon_haircut",
  "https://pokeheroes.com/sce",
  "https://pokeheroes.com/scs",
  "https://pokeheroes.com/seashellos",
  "https://pokeheroes.com/sell_items",
  "https://pokeheroes.com/sell_items.php",
  "https://pokeheroes.com/settings",
  "https://pokeheroes.com/shadowradar",
  "https://pokeheroes.com/share",
  "https://pokeheroes.com/skygift",
  "https://pokeheroes.com/sprites_house",
  "https://pokeheroes.com/square",
  "https://pokeheroes.com/stafflist",
  "https://pokeheroes.com/stats",
  "https://pokeheroes.com/stonks",
  "https://pokeheroes.com/stonks?p=venusaur%20(retro)",
  "https://pokeheroes.com/storage_box",
  "https://pokeheroes.com/style_settings",
  "https://pokeheroes.com/subforum?id=2",
  "https://pokeheroes.com/take_item.php",
  "https://pokeheroes.com/tall_grass",
  "https://pokeheroes.com/tall_grass.php",
  "https://pokeheroes.com/tenmillion",
  "https://pokeheroes.com/tindemera",
  "https://pokeheroes.com/toolshed",
  "https://pokeheroes.com/town",
  "https://pokeheroes.com/treasures",
  "https://pokeheroes.com/union_room",
  "https://pokeheroes.com/unown",
  "https://pokeheroes.com/use_vitamin.php?item=Rare%20Candy",
  "https://pokeheroes.com/user_polls",
  "https://pokeheroes.com/userboxes.php?name=Kimie",
  "https://pokeheroes.com/userboxes.php?name=Riako",
  "https://pokeheroes.com/userlist",
  "https://pokeheroes.com/userpokedex.php?name=Riako",
  "https://pokeheroes.com/userprofile?name=Kimie",
  "https://pokeheroes.com/userprofile?name=Riako",
  "https://pokeheroes.com/vday",
  "https://pokeheroes.com/warnings",
  "https://pokeheroes.com/weather",
  "https://pokeheroes.com/wondercards",
  "https://pokeheroes.com/wondercards.php",
  "https://pokeheroes.com/wormhole",
  "https://pokeheroes.com/zekrom",
  "https://pokeheroes.com/zygarde",
  "https://pokeheroes.com/profile_layout",
  "https://pokeheroes.com/profile_layout?editContacts#contactlinks",
  "https://pokeheroes.com/userpokedex.php?name=Kimie&amp;compare",
];
